FROM ping2ravi/storm:0.9.5_oracle_jdk7.80.15_ubuntu.14.04


MAINTAINER Ravi Sharma
# Ubuntu 14.04
# Java Version oracle_jdk7 update 80
# Storm Version 0.9.5
#     http://storm.apache.org/downloads.html
RUN ln -s /usr/bin/python3.4 /usr/bin/python
CMD storm supervisor
