FROM ping2ravi/storm:0.9.6_oracle_jdk8.66.17i_ubuntu.14.04


MAINTAINER Ravi Sharma
# Ubuntu 14.04
# Java Version oracle_jdk8 update 66
# Storm Version 0.9.6
#     http://storm.apache.org/downloads.html
RUN ln -s /usr/bin/python3.4 /usr/bin/python
CMD storm nimbus
