FROM ping2ravi/storm:0.10.1_oracle_jdk7.80.15_ubuntu.15.10


MAINTAINER Ravi Sharma
# Ubuntu 15.10
# Java Version oracle_jdk7 update 80
# Storm Version 0.10.1
#     http://storm.apache.org/downloads.html
RUN ln -s /usr/bin/python3.4 /usr/bin/python
CMD storm ui
