FROM ping2ravi/storm:0.9.5_oracle_jdk7.80.15_ubuntu.15.04


MAINTAINER Ravi Sharma
# Ubuntu 15.04
# Java Version oracle_jdk7 update 80
# Storm Version 0.9.5
#     http://storm.apache.org/downloads.html
CMD storm supervisor
