FROM ping2ravi/storm:1.2.2_oracle_jdk8.131.11_ubuntu.16.04


MAINTAINER Ravi Sharma
# Ubuntu 16.04
# Java Version oracle_jdk8 update 131
# Storm Version 1.2.2
#     http://storm.apache.org/downloads.html
CMD storm supervisor
