FROM ping2ravi/storm:0.9.5_oracle_jdk8.92.14_ubuntu.15.10


MAINTAINER Ravi Sharma
# Ubuntu 15.10
# Java Version oracle_jdk8 update 92
# Storm Version 0.9.5
#     http://storm.apache.org/downloads.html
RUN ln -s /usr/bin/python3.4 /usr/bin/python
CMD storm ui
