FROM ping2ravi/storm:1.2.2_oracle_jdk10.0.2_ubuntu.3.4


MAINTAINER Ravi Sharma
# Ubuntu 3.4
# Java Version oracle_jdk10 update 0
# Storm Version 1.2.2
#     http://storm.apache.org/downloads.html
CMD storm supervisor
