FROM ping2ravi/storm:1.0.1_oracle_jdk7.80.15_ubuntu.15.10


MAINTAINER Ravi Sharma
# Ubuntu 15.10
# Java Version oracle_jdk7 update 80
# Storm Version 1.0.1
#     http://storm.apache.org/downloads.html
CMD storm supervisor
