FROM ping2ravi/storm:0.9.6_oracle_jdk8.66.17i_ubuntu.15.10


MAINTAINER Ravi Sharma
# Ubuntu 15.10
# Java Version oracle_jdk8 update 66
# Storm Version 0.9.6
#     http://storm.apache.org/downloads.html
CMD storm ui
