FROM ping2ravi/storm:0.10.1_oracle_jdk8.92.14_ubuntu.15.10


MAINTAINER Ravi Sharma
# Ubuntu 15.10
# Java Version oracle_jdk8 update 92
# Storm Version 0.10.1
#     http://storm.apache.org/downloads.html
CMD storm ui
