FROM ping2ravi/storm:1.2.2_oracle_jdk8.181.13_ubuntu.3.4


MAINTAINER Ravi Sharma
# Ubuntu 3.4
# Java Version oracle_jdk8 update 181
# Storm Version 1.2.2
#     http://storm.apache.org/downloads.html
CMD storm ui
