FROM ping2ravi/storm:1.2.2_oracle_jdk8.131.11_ubuntu.15.10


MAINTAINER Ravi Sharma
# Ubuntu 15.10
# Java Version oracle_jdk8 update 131
# Storm Version 1.2.2
#     http://storm.apache.org/downloads.html
CMD storm ui
