FROM ping2ravi/storm:1.0.1_oracle_jdk7.80.15_ubuntu.15.04


MAINTAINER Ravi Sharma
# Ubuntu 15.04
# Java Version oracle_jdk7 update 80
# Storm Version 1.0.1
#     http://storm.apache.org/downloads.html
RUN ln -s /usr/bin/python3.4 /usr/bin/python
CMD storm nimbus
